# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f8a48e74bc0c401b1b9a35cd4f6554cde2e3d91401b753e34dec5dd105a218dd1802a9da54d5f5c6d82802e3a8e1836729d99ba96f49d08ed3c9ed42e8ad853

test:
  secret_key_base: 5ff3e402fbbe8825d10d7477f7b51abac4fc86a5d972fdc8184bdacf9508a41e56e1a26962e3323db117ac90c325fccc01d6ef7ebe7719acd14ff6e0e7f685a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
